// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: zync.proto

package zync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RestoreRequest provides the controller CID that contains
// metadata about which files to restore on the host
type RestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_zync_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// RestoreStatusUpdate contains the current status of the
// restore process
type RestoreStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PercentCompleted float64 `protobuf:"fixed64,1,opt,name=percent_completed,json=percentCompleted,proto3" json:"percent_completed,omitempty"`
}

func (x *RestoreStatusUpdate) Reset() {
	*x = RestoreStatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStatusUpdate) ProtoMessage() {}

func (x *RestoreStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_zync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStatusUpdate.ProtoReflect.Descriptor instead.
func (*RestoreStatusUpdate) Descriptor() ([]byte, []int) {
	return file_zync_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreStatusUpdate) GetPercentCompleted() float64 {
	if x != nil {
		return x.PercentCompleted
	}
	return 0
}

// BackupRequest is an empty message used to initiate the
// backup process
type BackupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_zync_proto_rawDescGZIP(), []int{2}
}

// BackupStatus contains the CID with the most up to date
// metadata about what is being stored in IPFS
type BackupStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *BackupStatus) Reset() {
	*x = BackupStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStatus) ProtoMessage() {}

func (x *BackupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_zync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStatus.ProtoReflect.Descriptor instead.
func (*BackupStatus) Descriptor() ([]byte, []int) {
	return file_zync_proto_rawDescGZIP(), []int{3}
}

func (x *BackupStatus) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

// RegexRequest is a request that provides an re2 compatible
// regex that is used for searching for matching files
// (https://github.com/google/re2/wiki/Syntax)
type RegexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern          string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	CurrentDirectory string `protobuf:"bytes,2,opt,name=current_directory,json=currentDirectory,proto3" json:"current_directory,omitempty"`
}

func (x *RegexRequest) Reset() {
	*x = RegexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexRequest) ProtoMessage() {}

func (x *RegexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexRequest.ProtoReflect.Descriptor instead.
func (*RegexRequest) Descriptor() ([]byte, []int) {
	return file_zync_proto_rawDescGZIP(), []int{4}
}

func (x *RegexRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *RegexRequest) GetCurrentDirectory() string {
	if x != nil {
		return x.CurrentDirectory
	}
	return ""
}

// File represents an individual file managed by zync
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid          string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	AbsolutePath string `protobuf:"bytes,2,opt,name=absolute_path,json=absolutePath,proto3" json:"absolute_path,omitempty"`
	Checksum     string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	IsDirectory  bool   `protobuf:"varint,4,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zync_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_zync_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_zync_proto_rawDescGZIP(), []int{5}
}

func (x *File) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *File) GetAbsolutePath() string {
	if x != nil {
		return x.AbsolutePath
	}
	return ""
}

func (x *File) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *File) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

var File_zync_proto protoreflect.FileDescriptor

var file_zync_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x7a, 0x79,
	0x6e, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x22, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x13, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x2b, 0x0a, 0x11, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x10, 0x70, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x0f, 0x0a,
	0x0d, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x20,
	0x0a, 0x0c, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64,
	0x22, 0x55, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x7c, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75,
	0x74, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73,
	0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73,
	0x75, 0x6d, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x32, 0xa3, 0x02, 0x0a, 0x04, 0x7a, 0x79, 0x6e, 0x63, 0x12, 0x32,
	0x0a, 0x08, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x7a, 0x79, 0x6e,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x30, 0x01, 0x12, 0x33, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12,
	0x15, 0x2e, 0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x65, 0x78, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x67, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e,
	0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x30, 0x01, 0x12, 0x37,
	0x0a, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x16, 0x2e, 0x7a, 0x79, 0x6e, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x42, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x12, 0x17, 0x2e, 0x7a, 0x79, 0x6e, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x7a, 0x79,
	0x6e, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x30, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x79, 0x6e, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x7a, 0x79, 0x6e,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zync_proto_rawDescOnce sync.Once
	file_zync_proto_rawDescData = file_zync_proto_rawDesc
)

func file_zync_proto_rawDescGZIP() []byte {
	file_zync_proto_rawDescOnce.Do(func() {
		file_zync_proto_rawDescData = protoimpl.X.CompressGZIP(file_zync_proto_rawDescData)
	})
	return file_zync_proto_rawDescData
}

var file_zync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_zync_proto_goTypes = []interface{}{
	(*RestoreRequest)(nil),      // 0: zync.v1.RestoreRequest
	(*RestoreStatusUpdate)(nil), // 1: zync.v1.RestoreStatusUpdate
	(*BackupRequest)(nil),       // 2: zync.v1.BackupRequest
	(*BackupStatus)(nil),        // 3: zync.v1.BackupStatus
	(*RegexRequest)(nil),        // 4: zync.v1.RegexRequest
	(*File)(nil),                // 5: zync.v1.File
}
var file_zync_proto_depIdxs = []int32{
	4, // 0: zync.v1.zync.AddFiles:input_type -> zync.v1.RegexRequest
	4, // 1: zync.v1.zync.ListFiles:input_type -> zync.v1.RegexRequest
	4, // 2: zync.v1.zync.DeleteFiles:input_type -> zync.v1.RegexRequest
	2, // 3: zync.v1.zync.Backup:input_type -> zync.v1.BackupRequest
	0, // 4: zync.v1.zync.Restore:input_type -> zync.v1.RestoreRequest
	5, // 5: zync.v1.zync.AddFiles:output_type -> zync.v1.File
	5, // 6: zync.v1.zync.ListFiles:output_type -> zync.v1.File
	5, // 7: zync.v1.zync.DeleteFiles:output_type -> zync.v1.File
	3, // 8: zync.v1.zync.Backup:output_type -> zync.v1.BackupStatus
	1, // 9: zync.v1.zync.Restore:output_type -> zync.v1.RestoreStatusUpdate
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zync_proto_init() }
func file_zync_proto_init() {
	if File_zync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreStatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackupStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zync_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zync_proto_goTypes,
		DependencyIndexes: file_zync_proto_depIdxs,
		MessageInfos:      file_zync_proto_msgTypes,
	}.Build()
	File_zync_proto = out.File
	file_zync_proto_rawDesc = nil
	file_zync_proto_goTypes = nil
	file_zync_proto_depIdxs = nil
}
